# Generated by Django 5.2.6 on 2025-09-14 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('scarves_banner', 'Scarves or Banners'), ('footballs', 'Collector Footballs'), ('autographed', 'Autographed Memorabilia'), ('second_hand', 'Second-Hand Collectible'), ('limited_edition', 'Limited Edition Item'), ('authentic_retail', 'Authentic Retail Jersey'), ('replica_jersey', 'Replica Jersey'), ('match_worn', 'Match-Worn Jersey')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=3)),
                ('edition_type', models.CharField(choices=[('replica', 'Replica'), ('limited', 'Limited Edition'), ('secondhand', 'Second Hand')], default='replica', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good')], default='new', max_length=20)),
                ('authenticity_certificate', models.BooleanField(default=False)),
                ('rarity_level', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='common', max_length=20)),
            ],
        ),
    ]
