# Generated by Django 5.2.6 on 2025-09-14 15:58

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('jersey', 'Jersey'), ('scarves_banner', 'Scarves or Banners'), ('footballs', 'Collector Footballs'), ('autographed', 'Autographed Memorabilia'), ('second_hand', 'Second-Hand Collectible'), ('limited_edition', 'Limited Edition Item'), ('authentic_retail', 'Authentic Retail Jersey'), ('replica_jersey', 'Replica Jersey'), ('match_worn', 'Match-Worn Jersey')], max_length=100),
        ),
    ]
