# Generated by Django 5.2.6 on 2025-09-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
