# Generated by Django 5.2.6 on 2025-09-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('scarves_banner', 'Scarves or Banners'), ('footballs', 'Collector Footballs'), ('autographed', 'Autographed Memorabilia'), ('second_hand', 'Second-Hand Collectible'), ('limited_edition', 'Limited Edition Item'), ('authentic_retail', 'Authentic Retail Jersey'), ('replica_jersey', 'Replica Jersey'), ('match_worn', 'Match-Worn Jersey')], default='jersey', max_length=20),
        ),
    ]
